ome/omero-cli-transfer

requirements.txt
src/generate_omero_objects.py
src/generate_xml.py
src/omero_cli_transfer.py
test/unit/test_set.py

Each imported image destination-side gets a `MapAnnotation` with the following characteristics:
namespace: `openmicroscopy.org/cli/transfer`
contents:
- `origin_image_id`: ID of image on the origin server
- `origin_hostname`; hostname of original server
- `packing_timestamp`:  DD/MM/YYYY HH:MM:SS timestamp of when this annotation was generated, origin-side
- `software`: code used to generate the package (just using `omero-cli-transfer`)
- `version`: software version (retrieved from `setup.py`)
- `zip_file_md5`: md5 sum of the zip file used for transfer

Added provenance metadata

---

.omero/docker
src/generate_omero_objects.py
src/generate_xml.py
src/omero_cli_transfer.py

Covers the use case in #8 - images without `OriginalFile`s get exported instead of downloaded, and everything else works more or less as-is.

Allowing for transfer of images without `OriginalFile`s

---

src/generate_xml.py
src/omero_cli_transfer.py

This PR fixes the issues reported in #12, namely:
1) Repeat imports are not an issue any longer. In addition to filtering IDs by `ClientPath` to retrieve IDs of images that were recently imported, we also filter by the existence of `MapAnnotation`s - fully-imported unpacks are annotated with provenance metadata, so previous runs of `unpack` are excluded from the list of IDs.
2) All images in a `Fileset` are added to the XML file - this avoids issues with things like packing a single image in an NDPI, or a Dataset with partial Filesets inside. Destination-side, the whole Fileset needs to be imported anyway, and any out-of-scope extra images from that import will now sit in Orphaned instead of breaking the workflow.

Enforcing whole filesets in XML files, filtering destination IDs

---

.omero/py-check
src/generate_omero_objects.py
src/generate_xml.py
src/omero_cli_transfer.py

This PR adds `CommentAnnotation`s, `LongAnnotation`s and `FileAnnotation`s. Since we're already using `CommentAnnotation`s to keep track of file locations for `Image`s, we also use the same for `FileAnnotation`s, with some extra logic to accommodate `omero download`'s different behavior between Filesets and OriginalFiles. There is no clash between these `CommentAnnotation`s and real ones, since these use negative unique IDs.
Current commit seems to do all of these correctly on local testing, but I will probably throw a few more cases at it next week before feeling good about a merge.

Extra annotations (Comments, Ratings, File Annotations)

---

src/omero_cli_transfer.py

Minor bug that went through: for images without underlying files, the filename building for exporting was not casting the ID number as a `str`, causing an exception. This should fix it.

casting ID of non-file image as str for export

---

src/omero_cli_transfer.py

This fixes the problem reported [here](https://forum.image.sc/t/errors-encountered-using-omero-cli-transfer/69852/7). Some images generate MapAnnotations on import time, and transfer was relying on just-imported images to have no annotations to detect which images required moving/annotating. We now check to see if the image has no annotation with namespace `'openmicroscopy.org/cli/transfer'`.

fixes imports that autogenerate annotations

---

src/omero_cli_transfer.py
test/integration/test_transfer.py

Added an extra `--skip` option to `omero transfer unpack` that passes through to `omero import`. Same options as import: `all`, `checksum`, `thumbnails`, `minmax` and `upgrade`.

added import `--skip` options

---

.omero/docker-compose.yml
README.md
requirements.txt
src/generate_omero_objects.py
src/omero_cli_transfer.py
test/integration/test_transfer.py

This PR includes:
- better tests, including a collection of tests that pack a target, unpack it and compare it to the original;
- a fix for #33 - plates that are imported as individual images are now collected into an actual plate
- a partial fix for #13 (again) - we're using the first `Shape` in an `ROI` to collect `fill_color` and `stroke_color`, and using `(0,0,0,0)` defaults in case these are not set

Better tests, fixing "dataset to plate" issue and ROI fill/strokecolors

---

.omero/py-setup
README.md
setup.py
src/generate_omero_objects.py
src/generate_xml.py
src/omero_cli_transfer.py

This PR covers #35 and the very last lingering effects of #13. It implements (rudimentary) RO-Crate exporting with an optional dependency and adds better defaults for `fillColor` on ROIs.

RO-crate support

---

README.md

Just noticed the install instructions have a typo: `conda-force` instead of `conda-forge`
Also, conda uses single `=` to specify versions, not `==` see:
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-packages
This is a quick fix, so copy-pasta works!
Edit: not sure what the spurious diff is for line 125, this was a quick edit using the GitHub web interface.

Fix typo in README.md (forge not force, and single =)

---

setup.py
src/generate_xml.py
test/data/prepare/transfer.xml

This fixes #59 ; `prepare` should now be using relative paths in its `transfer.xml`, and only reconstructing absolute paths when necessary. This should allow for a folder containing a `prepare`-generated XML to be moved around, imported in-place and so on, and `unpack` should be able to act upon that folder regardless of where it ends up.

prepare now uses relative paths

---

setup.py
src/generate_xml.py

`omero transfer prepare --filelist` now also uses relative paths for indicating image file locations in `transfer.xml`.

using relative paths for `--filelist` as well

---

README.md
setup.py
src/generate_xml.py
src/omero_cli_transfer.py
test/integration/test_transfer.py

this adds the sub-option `--simple` to `omero transfer pack`, generating a human-readable export where projects and datasets are represented by folders with the "ID_NAME" format.

Human readable pack

---

src/generate_omero_objects.py
src/generate_xml.py
src/omero_cli_transfer.py
test/integration/test_figure.py
test/integration/test_transfer.py

This update includes the `--figure` optional argument to `omero transfer pack` and `unpack`. On `pack`, it will include any figures that refer to any of the Images in the pack, and on `unpack` it will use any figures included in the pack, if any. 
The big caveats: 
- there _might_ be some impact on performance on the `pack` side, depending on how many Figures a user has access to. There's no efficient query for which Figures refer to an Image, so we need to download and search every Figure JSON to look for that.
- There's no guaranteed behavior for Figures that include images that are NOT in the pack. They might just not show up destination-side, you might get a permission error, you might end up getting a different image altogether displayed. Use carefully!

Packing and unpacking figures

---

README.md
src/omero_cli_transfer.py

As discussed in issue #68 I started the development of an omero-arc exporter: https://github.com/cmohl2013/omero-arc
Following a suggestion from @joshmoore, the ARC export function was not directly integrated into omero-cli-transfer.
Instead, a plugin interface was created in omero-cli-transfer. omero-arc exposes an entrypoint that can be consumed by omero-cli-transfer. 
* added optional argument `--plugin` in omero_cli_transfer.py 
* added plugin interface in omero_cli_transfer.py
* added some documentation in README.md to explain how plugins can developed and how it is used
Advantages: 
* The omero-arc is still in an early stage and changes will occur frequently. By not directly integrating to omero-cli-transfer, we avoid repeaded pull requests to omero-cli-transfer
* The changes in …

Added plugin interface for external packers

---

.github/workflows/upload_to_pypi.yml
.github/workflows/upload_to_test_pypi.yml

Minor change to publishing GH actions to that pre-releases are pushed to PyPI.

sets action to "published" so it runs on prereleases

---

.github/workflows/omero_plugin.yml
.omeroci/cli-build
README.md
requirements.txt
setup.py
src/omero_cli_transfer.py
test/integration/test_transfer.py

Previously, any failures of `omero download` when trying to download images (often due to binary permissions not allowing for them) were silent; a final pack would still be produced, only missing the relevant binary files. This PR implements checking return codes for all `omero download` and `omero export` operations, and fails/cleans up temp files in case any of them fails.

raising a `NonzeroReturnCode` when download fails

---

src/generate_omero_objects.py

This addresses #82 - in short, currently we have an undefined behavior regarding image IDs in Figures. for Images contained in a pack, references to their IDs are updated in transferred figures to point to the destination ID; for all other images in those figures, their IDs are untouched.
In practice, this can mean that Figures will have empty panels (in case the source ID for non-pack images do not exist/are outside permissions in the destination side) or have "wrong" images (in case the source ID is accessible destination-side). 
This PR changes all non-pack image IDs to `-1` - that ensures that 1) the inconsistent behavior described is eliminated, panels will always be empty; 2) clearly signals to users that this is a deliberate choice; 3) indicates that those images were not part of …

Making reference to image IDs not contained in a pack negative in Figures

---

src/generate_omero_objects.py
src/omero_cli_transfer.py
test/integration/test_transfer.py

This PR adds capability for packing multiple objects in a single file - both in the `Project:1-5` format (for projects 1 through 5) and `Project:1,3,5` (for projects 1, 3 and 5). Unpacking such a file should recreate all entities from the origin side. It also includes tests for this new feature.

packing list of objects

---

.omeroci/cli-build
.omeroci/py-setup
setup.py

Using the newer `pytest` interface instead of `python setup.py test`, which is not supported by newer setuptools versions.

using updated pytest interface

---

.omeroci/py-setup
setup.py
src/generate_xml.py

This addresses #87 , where a `Name` attribute wouldn't be set for a single-image `prepare` target when `showinf` returned an empty name string. New behavior is using the filename as image name.
edit: also sneaked in an update to dependencies.

dealing with empty `image.name` returned by `showinf` in `prepare` (also updating dependencies)

---

src/generate_xml.py

Due to a mis-indented line and a reused variable, sometimes duplicate omero.figure json content is downloaded to a different file's path.

Fix fileannotation download bug

---

src/generate_xml.py

ome_types already provides sequences to auto-generate element IDs. This change manipulates that counter rather than maintain our own.

Clean up annotation unique ID logic

---

.omeroci/cli-build
.omeroci/py-setup
setup.py
src/generate_omero_objects.py
src/generate_xml.py
src/omero_cli_transfer.py
test/data/prepare/transfer.xml
test/integration/test_prepare.py

This PR removes the `@gateway_required` decorator from `prepare`, allowing it to be run without a valid session on an OMERO server. (it also updates a few dependencies.)

updating deps, removing gateway requirement for prepare

---

.github/workflows/upload_to_pypi.yml
.github/workflows/upload_to_test_pypi.yml

Bumping the action to the release/v1 branch should include the latest stable patches and fix the release to PyPI

Use v1 to avoid issue when publishing

---

.github/workflows/upload_to_pypi.yml
.github/workflows/upload_to_test_pypi.yml
pyproject.toml
setup.py

Modernizing the build/install infra by moving everything to a `pyproject.toml` file. Also sets up the PyPI upload actions to use dynamic versioning retrieved from the Github release tags.

Use `pyproject.toml` instead of `setup.py`

---

requirements.txt

requirements.txt was out of date with actual version requirements for ezomero and ome-types based on the pyproject.toml

updated requirements to match pyproject
